import './globals.css'
import { Inter } from 'next/font/google'
import SupabaseProvider from './supabase-provider'
import Navbar from './layout/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SupabaseProvider>
        <body className={inter.className}>
          <Navbar/>
          
          {children}
        </body>
      </SupabaseProvider>
    </html>
  )
}
